apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-config
data:
  DB_HOST: "postgresql-service"   # use your postgres service name from `kubectl get svc`
  DB_USERNAME: "POSTGRES_USER"
  DB_NAME: "postgresql"
  DB_PORT: "5432"
