apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-config
data:
  DB_NAME: "postgresql"
  DB_USER: "mydatabase"
  DB_HOST: "mypassword"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==