apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-config
data:
  DB_NAME: " "
  DB_USER: " "
  DB_HOST: " "
  DB_PASSWORD : " "
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  DB_PASSWORD: 
