apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
  - port: 5153
    targetPort: 5153

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
      - name: coworking
        image: 296062569552.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics
        imagePullPolicy: Always
        ports:
        - containerPort: 5153
        envFrom:
        - configMapRef:
            name: coworking-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: DB_PASSWORD
        readinessProbe:
          httpGet:
            path: /readiness_check
            port: 5153
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
